set_property SRC_FILE_INFO {cfile:C:/Users/FAMILY/Desktop/PUF_5_1/src/xdc/pin.xdc rfile:../../../../../../src/xdc/pin.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/FAMILY/Desktop/PUF_5_1/src/xdc/area.xdc rfile:../../../../../../src/xdc/area.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/FAMILY/Desktop/PUF_5_1/src/xdc/puf_loc.xdc rfile:../../../../../../src/xdc/puf_loc.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/FAMILY/Desktop/PUF_5_1/src/xdc/debug.xdc rfile:../../../../../../src/xdc/debug.xdc id:4} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports iclk]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D10 [get_ports uart_txd]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_1
add_cells_to_pblock [get_pblocks pblock_1] [get_cells -quiet [list system_i/arbiter_puf_0]]
resize_pblock [get_pblocks pblock_1] -add {SLICE_X0Y101:SLICE_X35Y114}
resize_pblock [get_pblocks pblock_1] -add {DSP48_X0Y42:DSP48_X0Y45}
resize_pblock [get_pblocks pblock_1] -add {RAMB18_X0Y42:RAMB18_X0Y45}
resize_pblock [get_pblocks pblock_1] -add {RAMB36_X0Y21:RAMB36_X0Y22}
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_2
add_cells_to_pblock [get_pblocks pblock_2] [get_cells -quiet [list system_i/axi_gpio_0 system_i/axi_gpio_1 system_i/axi_uartlite_0 system_i/h_clk_rst system_i/mdm_1 system_i/microblaze_0 system_i/microblaze_0_axi_periph system_i/microblaze_0_local_memory]]
resize_pblock [get_pblocks pblock_2] -add {SLICE_X36Y51:SLICE_X65Y85}
resize_pblock [get_pblocks pblock_2] -add {DSP48_X1Y22:DSP48_X1Y33}
resize_pblock [get_pblocks pblock_2] -add {RAMB18_X1Y22:RAMB18_X2Y33}
resize_pblock [get_pblocks pblock_2] -add {RAMB36_X1Y11:RAMB36_X2Y16}
set_property src_info {type:XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[1].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[1].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[1].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X1Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[1].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[2].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[2].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[2].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X2Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[2].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[3].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[3].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[3].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X3Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[3].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[4].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[4].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[4].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X4Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[4].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[5].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[5].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[5].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X5Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[5].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[6].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[6].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[6].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X6Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[6].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[7].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[7].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[7].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X7Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[7].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[8].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X8Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[8].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[8].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X8Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[8].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[9].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[9].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[9].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X9Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[9].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[10].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X10Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[10].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[10].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X10Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[10].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[11].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X11Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[11].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[11].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X11Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[11].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[12].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X12Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[12].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[12].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X12Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[12].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[13].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X13Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[13].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[13].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X13Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[13].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[14].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X14Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[14].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[14].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X14Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[14].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[15].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X15Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[15].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[15].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X15Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[15].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[16].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X16Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[16].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[16].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X16Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[16].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[17].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X17Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[17].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[17].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X17Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[17].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[18].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X18Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[18].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[18].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X18Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[18].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[19].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X19Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[19].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[19].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X19Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[19].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[20].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X20Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[20].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[20].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X20Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[20].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[21].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X21Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[21].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[21].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X21Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[21].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[22].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X22Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[22].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[22].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X22Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[22].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[23].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X23Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[23].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[23].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X23Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[23].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[24].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X24Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[24].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[24].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X24Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[24].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[25].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X25Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[25].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[25].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X25Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[25].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[26].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X26Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[26].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[26].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X26Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[26].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[27].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X27Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[27].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[27].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X27Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[27].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[28].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[28].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[28].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X28Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[28].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[29].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[29].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[29].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[29].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[30].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[30].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[30].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X30Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[30].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[31].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X31Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[31].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[31].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X31Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[31].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL D6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[32].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X32Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[32].inst_mux_1/oout_INST_0}]
set_property src_info {type:XDC file:3 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[32].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X32Y101 [get_cells {system_i/arbiter_puf_0/U0/inst_delay_line/inst_mux_pair[32].inst_mux_2/oout_INST_0}]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL B5FF [get_cells system_i/arbiter_puf_0/U0/inst_dff/dff_primitive.dff_inst]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X32Y101 [get_cells system_i/arbiter_puf_0/U0/inst_dff/dff_primitive.dff_inst]
set_property src_info {type:XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_5]
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_9]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_10]
set_property src_info {type:XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_11]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:4 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:4 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:4 line:15 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_i/h_clk_rst/clk_wiz_1/inst/oclk_out1]]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:4 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_5]]
set_property src_info {type:XDC file:4 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_9]]
set_property src_info {type:XDC file:4 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_10]]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/axi_gpio_1/U0/AXI_LITE_IPIF_I_n_11]]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
