# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/system_ila_0_0.xci
# IP: The module: 'system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/system_ila_0_0.xci
# IP: The module: 'system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/FAMILY/Desktop/PUF_5_1/src/bd/system/ip/system_ila_0_0/system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
